// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmko0wqWf7_sCIpNzUJbHXq-sMRJMCBts',
    appId: '1:26919668975:web:29a874ff9b13b549791f1a',
    messagingSenderId: '26919668975',
    projectId: 'test2-67b18',
    authDomain: 'test2-67b18.firebaseapp.com',
    storageBucket: 'test2-67b18.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxCyc0idGeyQf9IW9nEGHOgryu4wiRHrE',
    appId: '1:26919668975:android:a46d0c19bd29f28c791f1a',
    messagingSenderId: '26919668975',
    projectId: 'test2-67b18',
    storageBucket: 'test2-67b18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUtOnDd0-Khttjj7pkBclI9Ye7_kLTjgA',
    appId: '1:26919668975:ios:7089f101b9f51567791f1a',
    messagingSenderId: '26919668975',
    projectId: 'test2-67b18',
    storageBucket: 'test2-67b18.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUtOnDd0-Khttjj7pkBclI9Ye7_kLTjgA',
    appId: '1:26919668975:ios:03738f1713c5cedd791f1a',
    messagingSenderId: '26919668975',
    projectId: 'test2-67b18',
    storageBucket: 'test2-67b18.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
